# -*- coding: utf-8 -*-
"""kadai_015.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T_QVOqG6ysTx8B5VP5PDikwI3aVoE8bs
"""

class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def printinfo(self):
        print(f"Name: {self.name}, Age: {self.age}")

# Humanクラスのインスタンスを作成
person = Human("Taro", 30)

# printinfoメソッドを使用して、名前と年齢を出力
person.printinfo()