# -*- coding: utf-8 -*-
"""kadai_008.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWALdZTUZtuRYKKtGBMqJd6nygONNA2S
"""

#ランダムな整数を利用するために、randomモジュールをインポート
import random

# 変数numに0～100までのランダムな整数を代入する
var = random.randint(0, 100)

# 3の倍数と5の倍数の両方に該当する場合
if var % 3 == 0 and var % 5 == 0:
    print("FizzBuzz")

# 3の倍数にのみ該当する場合
elif var % 3 == 0:
    print("Fizz")

# 5の倍数にのみ該当する場合
elif var % 5 == 0:
    print("Buzz")

# 上記のどの条件にも該当しない場合
else:
    print(var)