# -*- coding: utf-8 -*-
"""kadai_017.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G8ohEUy66lDZAgq-5btybN5I_znpf9ie
"""

class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def check_adult(self):
        if self.age >= 20:
            print(f"{self.name}は大人です。")
        else:
            print(f"{self.name}は大人ではない。")

# Humanクラスのインスタンスを生成してリストに追加
humans = [
    Human("山田太郎", 25),
    Human("鈴木一郎", 18),
    Human("佐藤花子", 20),
]

# リストの要素数分だけcheck_adultメソッドを呼び出す
for human in humans:
    human.check_adult()